---
# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-argo
  namespace: prod
  labels:
    app: nginx-argo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-argo
  template:
    metadata:
      labels:
        app: nginx-argo
    spec:
      containers:
        - name: nginx
          image: rifqoi:v0.1.3
          ports:
            - containerPort: 80
